### ISSUE TITLE
Using this to input analog RGB into a PVM/CRT that has only TTL RGB

### ISSUE THREAD

**Issue by bassybeats** [wurthless-elektroniks/tv-desecrator#1]
Could this be used to inject analog RGB into a TTL PVM? I have a JVC-TM90PSN that only has TTL RGB/CGA in. But if you look at the schematics it looks like it gets converted internally back to analog RGB.

TTL is useless for me so was thinking this project might/could work? 

![Where it needs to be inserted](https://github.com/user-attachments/assets/d98f5509-36f2-4286-bfb6-b443e9838c7d)

**Comment by wurthless-elektroniks** [comment]
This isn't the mod you're looking for. The TV Desecrator is only meant to multiplex 0.7Vpp-level analog video and not TTL video.

Looking at the schematic, it appears that what you're trying to do is inject RGB video onto the main RGB line drives, which connect directly to the neckboard. This is dangerous and you should never try doing this. (I have a Sony PVM that is composite only and can't be modified except through this method, which is why I won't mod it.)

The following is merely guesswork and not actual advice.

The 74LS09 is an AND chip being abused as a buffer. I think this is strictly "digital" RGB in that each red/green/blue value can only be a logical 1 or a 0. The drive transistors most likely won't accept anything other than a high or low signal, so anything that goes up to 0.7 volts might not turn those transistors on fully, and that rules out injection in the "right" place.

Your best bet is to find another display.
